<a href="https://colab.research.google.com/github/adimali095/agroguide-megaproject/blob/main/pytorchShort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [146]:
import torch
import numpy as np
import pandas as pd

In [147]:
x = torch.empty(1)
print(x)
x = torch.empty(3)
print(x)
x = torch.empty(3,3)
print(x)

tensor([-1.5410e+35])
tensor([-1.5410e+35,  4.5817e-41, -1.5410e+35])
tensor([[ 6.6884e+31,  3.2925e-41,  4.3832e+31],
        [ 3.2925e-41,  4.4842e-44,  0.0000e+00],
        [ 6.7262e-44,  0.0000e+00, -1.6512e-02]])


In [148]:
x = torch.rand(1)
print(x)

tensor([0.3264])


In [149]:
x = torch.zeros(1)
print(x)

tensor([0.])


In [150]:
x = torch.ones(1)
print(x)

tensor([1.])


In [151]:
print(x.size(),x.shape)

torch.Size([1]) torch.Size([1])


In [152]:
print(x.dtype)

torch.float32


In [153]:
x = torch.tensor(torch.rand(5),requires_grad = True)
x

<ipython-input-153-2f36be730835>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(torch.rand(5),requires_grad = True)


tensor([0.1520, 0.6517, 0.8072, 0.9744, 0.2807], requires_grad=True)

In [154]:
x = torch.rand(4,4)
x

tensor([[0.3418, 0.2752, 0.7498, 0.2549],
        [0.3787, 0.3492, 0.9741, 0.3253],
        [0.3560, 0.9379, 0.4900, 0.5052],
        [0.2509, 0.3725, 0.4092, 0.1452]])

In [155]:
y = x.view(2,-1)
y

tensor([[0.3418, 0.2752, 0.7498, 0.2549, 0.3787, 0.3492, 0.9741, 0.3253],
        [0.3560, 0.9379, 0.4900, 0.5052, 0.2509, 0.3725, 0.4092, 0.1452]])

In [156]:
n = x.numpy()
n

array([[0.34177774, 0.27518684, 0.7497692 , 0.25486124],
       [0.37868017, 0.34920436, 0.9741259 , 0.3253485 ],
       [0.3560065 , 0.93789375, 0.49001122, 0.50518495],
       [0.25093615, 0.37253886, 0.4091648 , 0.1451745 ]], dtype=float32)

In [157]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
t = torch.tensor(n).to(device)

In [158]:
t.device

device(type='cpu')

In [159]:
x = torch.rand(2,requires_grad = True)
y = x+2
z = x*x
a = x/x
b = x.mean()
print(x,y,z,a,b,sep = "\n")

tensor([0.4421, 0.8487], requires_grad=True)
tensor([2.4421, 2.8487], grad_fn=<AddBackward0>)
tensor([0.1954, 0.7203], grad_fn=<MulBackward0>)
tensor([1., 1.], grad_fn=<DivBackward0>)
tensor(0.6454, grad_fn=<MeanBackward0>)


In [160]:
y.grad_fn

In [161]:
b.backward()
x.grad # db/dx

tensor([0.5000, 0.5000])

In [162]:
a = torch.rand(2,2)
b = (a*a).sum()
print(a.requires_grad)
print(b.grad_fn)
a.requires_grad_(True)
b = (a*a).sum()
print(a.requires_grad)
print(b.requires_grad)
print(b.grad_fn)


False
None
True
True


In [163]:
#three methods :
a = torch.tensor([1,1],dtype = torch.float32,requires_grad = True)

print(a.requires_grad)


# 1 using requires_grad_()
a.requires_grad_(False)
print("REQUIRES GRAD : ")
print(a.requires_grad)
a.requires_grad_(True)

'''
requires_grad_():
This method is used to modify the requires_grad attribute in-place
'''


# 2 using detach() function
print("\nDETACH() :")
b = a.detach() #return another tensor
print(b.requires_grad)
'''
detach():
The detach() method creates a new tensor with the same data
but without the gradient computation history.
This detached tensor (b) will not contribute
to gradient computation when used in further operations.

'''


# 3 wrapping in torch.no_grad()
print("\nTORCH.NO_GRAD()")
print(a.requires_grad)
with torch.no_grad() :
  b = a*a
  print(b.requires_grad)
'''
torch.no_grad():
The torch.no_grad() context manager is used to temporarily disable gradient computation.
'''


#4 wrapping in torch.inference_mode()
print("\nTORCH.INFERENCE_MODE")
print(a.requires_grad)
with torch.inference_mode() :
  b = a*a
  print(b.requires_grad)
'''
torch.inference_mode():
Introduced in PyTorch 1.10.0,
torch.inference_mode() is similar to torch.no_grad()
but also disables certain runtime checks and may optimize the computation
'''

True
REQUIRES GRAD : 
False

DETACH() :
False

TORCH.NO_GRAD()
True
False

TORCH.INFERENCE_MODE
True
False


'\ntorch.inference_mode(): \nIntroduced in PyTorch 1.10.0, \ntorch.inference_mode() is similar to torch.no_grad() \nbut also disables certain runtime checks and may optimize the computation\n'

# ***Linear regresion***

f(x) = w * x + b

approximating  
f(x) = 2 * x + 0
w = 2
b = 0

In [164]:
#creating dataset
weight =2
b =0
x = []
y = []
for i in range(10) :
  y.append(weight*i + b)
  x.append(i)
print(x[:5],y[:5])

[0, 1, 2, 3, 4] [0, 2, 4, 6, 8]


In [180]:
X = torch.tensor(x,dtype = torch.float32)
Y = torch.tensor(y,dtype = torch.float32)
W = torch.tensor(0.0,dtype = torch.float32,requires_grad=True)

#model output
def forward(X) :
  return W * X

#loss = MSE (Mean Squared Error)
def loss(y,y_pred) :
  return ((y-y_pred)**2).mean()

X_test = 5.0
print("Prediction BEFORE training : ",forward(X_test).item())

Prediction BEFORE training :  0.0


In [181]:
#Training
learning_rate = 0.01
n_epochs = 100

for epoch in range(n_epochs) :

  #predict forward pass
  y_pred = forward(X)

  #loss
  l = loss(Y,y_pred)

  #calculate gradients
  l.backward()

  with torch.no_grad() :
    W -= learning_rate * W.grad
  W.grad.zero_()

  if(epoch % 10 == 0) :
    print("epoch : ",epoch,"\tw = ",W.item(),"\tloss = ",l.item())


epoch :  0 	w =  1.1399999856948853 	loss =  114.0
epoch :  10 	w =  1.9998141527175903 	loss =  5.32592002855381e-06
epoch :  20 	w =  2.0 	loss =  7.801759455486335e-13
epoch :  30 	w =  2.0 	loss =  0.0
epoch :  40 	w =  2.0 	loss =  0.0
epoch :  50 	w =  2.0 	loss =  0.0
epoch :  60 	w =  2.0 	loss =  0.0
epoch :  70 	w =  2.0 	loss =  0.0
epoch :  80 	w =  2.0 	loss =  0.0
epoch :  90 	w =  2.0 	loss =  0.0


In [182]:
print(forward(X_test).item())

10.0
